import Link from "next/link";
import { notFound } from "next/navigation";
import { TopologyPreview } from "@/components/TopologyPreview";
import { AdvisorPanel } from "@/components/AdvisorPanel";
import { Logo, StatusDot } from "@/components/Logo";
import { IconArrowRight, IconEye, IconNetwork } from "@/components/icons";
import { getShareBundle } from "@/lib/queries";
import type { AdvisorResult } from "@/lib/types";

export const dynamic = "force-dynamic";

export default async function SharePage({
  params,
}: {
  params: Promise<{ shareId: string }>;
}) {
  const { shareId } = await params;
  const bundle = await getShareBundle(shareId);
  if (!bundle) notFound();

  const advisorResult: AdvisorResult = {
    suggestions: bundle.suggestions,
    engine: (bundle.engine as "openai" | "rules") || "rules",
    score: bundle.score ? Number(bundle.score) : 0,
    summary: bundle.summary || "",
  };

  const healthy = bundle.services.filter((s) => s.status === "RUNNING").length;

  return (
    <main className="min-h-screen">
      <header className="border-b border-edge/70 bg-base/70 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3.5">
          <Link href="/">
            <Logo />
          </Link>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-edge bg-panel/60 px-3 py-1 text-[11px] text-ink-dim">
            <IconEye width={13} height={13} /> Read-only snapshot
          </span>
        </div>
      </header>

      <section className="mx-auto max-w-7xl px-5 py-8">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-ink">{bundle.name}</h1>
            <p className="mt-1 flex items-center gap-3 text-[12.5px] text-ink-mute">
              <span className="inline-flex items-center gap-1.5">
                <StatusDot status="RUNNING" size={7} /> {healthy}/{bundle.services.length}{" "}
                healthy
              </span>
              <span>
                snapshot ·{" "}
                {new Date(bundle.takenAt).toLocaleString(undefined, {
                  dateStyle: "medium",
                  timeStyle: "short",
                })}
              </span>
            </p>
          </div>
          <Link
            href="/"
            className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-public to-private px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-public/20 transition-transform hover:scale-[1.03]"
          >
            Connect your own <IconArrowRight width={15} height={15} />
          </Link>
        </div>

        <div className="mt-6 zp-panel rounded-2xl p-4">
          <div className="mb-3 flex items-center gap-2">
            <IconNetwork width={16} height={16} className="text-public" />
            <h2 className="text-sm font-semibold text-ink">Service topology</h2>
          </div>
          <TopologyPreview services={bundle.services} />
        </div>

        <div className="mt-5">
          <AdvisorPanel result={advisorResult} loading={false} />
        </div>

        <div className="mt-8 rounded-xl border border-edge bg-panel/40 px-5 py-4 text-center text-[12.5px] text-ink-mute">
          This snapshot was generated by{" "}
          <Link href="/" className="font-semibold text-public hover:underline">
            ZeroPulse
          </Link>{" "}
          — the live architecture map + AI advisor for Zerops.
        </div>
      </section>
    </main>
  );
}
